### ISSUE TITLE
The implementation of the GetCompositeSchedule use case.

### ISSUE THREAD

**Issue by JamesLebron** [c-jimenez/open-ocpp#133]
Dear author, hello. Your open-source OCPP library has been very helpful to me, and I would like to express my respect and gratitude to you. I have a small question about the "GetCompositeSchedule" use case. I would like to ask why it doesn't support a value of 0（whole chargepoint）. Is it due to technical limitations or other reasons?

**Comment by c-jimenez** [comment]
Hello,

Thanks for your interest in this library.

I'm not much sure on how to process this request for connector 0 : should I take only ChargePointMaxProfile charging profile and/or should I take into account also the restrictions on the other connectors since the charging setpoint of the whole charging station will be at max the sum of the setpoints of its connectors?

So I keep looking for answers about this before implementing anything.

If you have some information, I'm all ears!

Regards

**Comment by JamesLebron** [comment]
I'm sorry, but I don't have any additional information about "using connector 0". 

May I know if you have an instant messaging software or email address, such as WhatsApp, Telegram, Facebook Messenger, Skype, or WeChat? If that's not convenient for you, email is also fine. 

Regarding this repository, I have found some bugs that I would like to report to you. Additionally, if I have any further information or suggestions, I would be happy to provide prompt feedback to you.

**Comment by c-jimenez** [comment]
Sorry for the delay,
I don't have any messaging account, so if its ok for you, we can keep exchanging using github conversations.
Feel free to open an issue for each bug you have encountered or for each improvement you may have, we can discuss about it in the corresponding conversations.
